when:
  - event: push
    branch: woodpecker-test
  - event: manual
    branch: woodpecker-test
  - event: tag  

steps:
  - name: echo
    image: debian
    commands:
      - echo "This is the build step"
  - name: build
    image: eclipse-temurin:11
    commands:
      - bash ./gradlew build --no-watch-fs
      - ls build/libs
  - name: publish
    image: woodpeckerci/plugin-release
    settings:
      files:
        - 'build/libs/*.jar'
    when:
    - event: tag
